language: r

#Define multiple R-versions, one from bioconductor
r:
  - oldrel
  - release
  - devel
  - bioc-devel

os:
  - linux
  - osx

cache: packages

# safelist
branches:
  only:
  - develop
  - master
